package br.com.furukawa.enums

enum TipoLogOperacao {
    ALTERAR_SENHA_USUARIO,
    FECHAR_LOTE_INCOMPLETO,
    IMPRIMIR_ETIQUETA_OF,
    REIMPRESSAO_ETIQUETA_SERIAL,
    ESTORNAR_APONTAMENTO,
    ESTORNAR_APONTAMENTO_OF,
    LIBERAR_OF,
    ENVIAR_OF_PARA_SEPARACAO,
    DIVIDIR_LOTE,
    AGRUPAR_LOTE,
    DIVIDIR_PARADA,
}
