// LOGIN - LOGOUT
export const CHANGE_SESSION_STATE = "CHANGE_SESSION_STATE";
export const LOGIN_REQUEST = "@login/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "@login/LOGIN_SUCCESS";
export const LOGIN_ERROR = "@login/LOGIN_ERROR";
export const LOGIN_CLEAN = "@login/LOGIN_CLEAN";
export const LOGIN_PERMISSAO_REQUEST = "@login/PERMISSAO_REQUEST";
export const LOGIN_PERMISSAO_SUCCESS = "@login/PERMISSAO_SUCCESS";
export const LOGIN_SET_LANGUAGE = "@login/SET_LANGUAGE_REQUEST";
export const LOGIN_INITIAL_SHAKE = "@login/INITIAL_SHAKE";
export const LOGIN_RESET_SHAKE = "@login/SET_RESET_SHAKE";
export const LOGIN_SET_VALUES = "@login/SET_VALUES";
export const LOGOUT = "@logout/LOGOUT";

// ALERTA
export const CHANGE_ALERTS_STATE = "CHANGE_ALERTS_STATE";

//USER
export const USER_LIST_ALL_REQUEST = "@user/LIST_ALL_REQUEST";
export const USER_LIST_ALL_SUCCESS = "@user/LIST_ALL_SUCCESS";
export const USER_DELETE_REQUEST = "@user/DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "@user/DELETE_SUCCESS";
export const USER_ATIVAR_OU_DESATIVAR_REQUEST = "@user/ATIVAR_DESATIVAR_REQUEST";
export const USER_SALVAR_REQUEST = "@user/SALVAR_REQUEST";
export const USER_SALVAR_SUCCESS = "@user/SALVAR_SUCCESS";
export const USER_EDITAR_REQUEST = "@user/EDITAR_REQUEST";
export const USER_EDITAR_SUCCESS = "@user/EDITAR_SUCCESS";
export const USER_ALTERAR_REQUEST = "@user/ALTERAR_REQUEST";
export const USER_ALTERAR_SUCCESS = "@user/ALTERAR_SUCCESS";
export const USER_CURRENT_REQUEST = "@user/CURRENT_REQUEST";
export const USER_CURRENT_SUCCESS = "@user/CURRENT_SUCCESS";
export const USER_SET_COLUNAS_REQUEST = "@user/SET_COLUNAS_REQUEST";
export const USER_SET_COLUNAS_SUCCESS = "@user/SET_COLUNAS_SUCCESS";
export const USER_GET_COLUNAS_REQUEST = "@user/GET_COLUNAS_REQUEST";
export const USER_GET_COLUNAS_SUCCESS = "@user/GET_COLUNAS_SUCCESS";
export const USER_ERROR = "@user/ERROR";
export const USER_PREPARAR_NOVO_REQUEST = "@user/PREPARAR_NOVO_REQUEST";
export const USER_PREPARAR_NOVO_SUCCESS = "@user/PREPARAR_NOVO_SUCCESS";
export const USER_PREPARAR_EDITAR_REQUEST = "@user/PREPARAR_EDITAR_REQUEST";
export const USER_PREPARAR_EDITAR_SUCCESS = "user/PREPARAR_EDITAR_SUCCESS";
export const USER_PREPARAR_EDITAR_PERFIL_REQUEST = "@user/PREPARAR_EDITAR_PERFIL_REQUEST";
export const USER_PREPARAR_EDITAR_PERFIL_SUCCESS = "@user/PREPARAR_EDITAR_PERFIL_SUCCESS";
export const USER_GET_ACESSOS_USUARIO_LOGADO_REQUEST = "@user/GET_ACESSOS_USUARIO_LOGADO_REQUEST";
export const USER_GET_ACESSOS_USUARIO_LOGADO_SUCCESS = "@user/GET_ACESSOS_USUARIO_LOGADO_SUCCESS";
export const USER_GRUPO_RECURSO_REQUEST = "@user/GRUPO_RECURSO_REQUEST";
export const USER_GRUPO_RECURSO_SUCCESS = "@user/GRUPO_RECURSO_SUCCESS";
export const USER_RECURSO_REQUEST = "@user/RECURSO_REQUEST";
export const USER_RECURSO_SUCCESS = "@user/RECURSO_SUCCESS";
export const USER_SET_USER_DATA = "@user/SET_USER_DATA";

// AUDITORIA
export const AUDITORIA_LIST_REQUEST = "@auditoria/LIST_REQUEST";
export const AUDITORIA_LIST_SUCCESS = "@auditoria/LIST_SUCCESS";
export const AUDITORIA_GET_ID_REQUEST = "@auditoria/GET_ID_REQUEST";
export const AUDITORIA_GET_ID_SUCCESS = "@auditoria/GET_ID_SUCCESS";
export const AUDITORIA_ERROR = "@auditoria/ERROR";

// LOG OPERACAO
export const LOG_OPERACAO_LIST_REQUEST = "@logOperacao/LIST_REQUEST";
export const LOG_OPERACAO_LIST_SUCCESS = "@logOperacao/LIST_SUCCESS";
export const LOG_OPERACAO_SALVAR_REQUEST = "@logOperacao/SALVAR_REQUEST";
export const LOG_OPERACAO_SALVAR_SUCCESS = "@logOperacao/SALVAR_SUCCESS";
export const LOG_OPERACAO_GET_ID_REQUEST = "@logOperacao/GET_ID_REQUEST";
export const LOG_OPERACAO_GET_ID_SUCCESS = "@logOperacao/GET_ID_SUCCESS";
export const LOG_OPERACAO_ERROR = "@logOperacao/ERROR";

// PERFIL
export const PERFIL_LIST_REQUEST = "@perfil/LIST_REQUEST";
export const PERFIL_LIST_SUCCESS = "@perfil/LIST_SUCCESS";
export const PERFIL_SALVAR_REQUEST = "@perfil/SALVAR_REQUEST";
export const PERFIL_SALVAR_SUCCESS = "@perfil/SALVAR_SUCCESS";
export const PERFIL_EDITAR_REQUEST = "@perfil/EDITAR_REQUEST";
export const PERFIL_EDITAR_SUCCESS = "@perfil/EDITAR_SUCCESS";
export const PERFIL_DELETE_REQUEST = "@perfil/DELETE_REQUEST";
export const PERFIL_DELETE_SUCCESS = "@perfil/DELETE_SUCCESS";
export const PERFIL_ERROR = "@perfil/ERROR";
export const PERFIL_PREPARAR_EDITAR_REQUEST = "@perfil/PREPARAR_EDITAR_REQUEST";
export const PERFIL_PREPARAR_EDITAR_SUCCESS = "@perfil/PREPARAR_EDITAR_SUCCESS";
export const PERFIL_PREPARAR_NOVO_REQUEST = "@perfil/PREARAR_NOVO_REQUEST";
export const PERFIL_PREPARAR_NOVO_SUCCESS = "@perfil/PREPARAR_NOVO_SUCCESS";

//ORGANIZACAO
export const ORGANIZACAO_LIST_REQUEST = "@organizacao/LIST_REQUEST";
export const ORGANIZACAO_LIST_SUCCESS = "@organizacao/LIST_SUCCESS";
export const ORGANIZACAO_SET = "@organizacao/SET_ORGANIZACAO";
export const ORGANIZACAO_SET_SUCESS = "@organizacao/SET_ORGANIZACAO_SUCESS";
export const ORGANIZACAO_SET_FORNECEDOR_REQUEST = "@organizacao/SET_FORNECEDOR_REQUEST";
export const ORGANIZACAO_SET_FORNECEDOR_SUCCESS = "@organizacao/SET_FORNECEDOR_SUCCESS";
export const ORGANIZACAO_ERROR = "@organizacao/ERROR";
export const ORGANIZACAO_GET_ACESSOS_USUARIO_LOGADO_REQUEST = "@organizacao/GET_ACESSOS_USUARIO_LOGADO_REQUEST";
export const ORGANIZACAO_GET_ACESSOS_USUARIO_LOGADO_SUCCESS = "@organizacao/GET_ACESSOS_USUARIO_LOGADO_SUCCESS";

//RECURSO
export const RECURSO_LIST_REQUEST = "@recurso/LIST_REQUEST";
export const RECURSO_LIST_SUCCESS = "@recurso/LIST_SUCCESS";
export const RECURSO_PREPARAR_NOVO_REQUEST = "@recurso/PREPARAR_NOVO_REQUEST";
export const RECURSO_PREPARAR_NOVO_SUCCESS = "@recurso/PREPARAR_NOVO_SUCCESS";
export const RECURSO_PREPARAR_EDITAR_REQUEST = "@recurso/PREPARAR_EDITAR_REQUEST";
export const RECURSO_PREPARAR_EDITAR_SUCCESS = "@recurso/PREPARAR_EDITAR_SUCCESS";
export const RECURSO_PREPARAR_CLONAR_REQUEST = "@recurso/PREPARAR_EDITAR_REQUEST";
export const RECURSO_PREPARAR_CLONAR_SUCCESS = "@recurso/PREPARAR_EDITAR_SUCCESS";
export const RECURSO_SALVAR_REQUEST = "@recurso/SALVAR_REQUEST";
export const RECURSO_SALVAR_SUCCESS = "@recurso/SALVAR_SUCCESS";
export const RECURSO_EDITAR_REQUEST = "@recurso/EDITAR_REQUEST";
export const RECURSO_EDITAR_SUCCESS = "@recurso/EDITAR_SUCCESS";
export const RECURSO_DELETE_REQUEST = "@recurso/DELETE_REQUEST";
export const RECURSO_DELETE_SUCCESS = "@recurso/DELETE_SUCCESS";
export const RECURSO_ATIVAR_OU_DESATIVAR_REQUEST = "@recurso/ATIVAR_DESATIVAR_REQUEST";
export const RECURSO_CLONAR_REQUEST = "@recurso/CLONAR_REQUEST";
export const RECURSO_CLONAR_SUCCESS = "@recurso/CLONAR_SUCCESS";
export const RECURSO_ERROR = "@recurso/ERROR";

//IMPRESSORA
export const IMPRESSORA_LIST_REQUEST = "@impressora/LIST_REQUEST";
export const IMPRESSORA_LIST_SUCCESS = "@impressora/LIST_SUCCESS";
export const IMPRESSORA_PREPARAR_NOVO_REQUEST = "@impressora/PREPARAR_NOVO_REQUEST";
export const IMPRESSORA_PREPARAR_NOVO_SUCCESS = "@impressora/PREPARAR_NOVO_SUCCESS";
export const IMPRESSORA_PREPARAR_EDITAR_REQUEST = "@impressora/PREPARAR_EDITAR_REQUEST";
export const IMPRESSORA_PREPARAR_EDITAR_SUCCESS = "@impressora/PREPARAR_EDITAR_SUCCESS";
export const IMPRESSORA_SALVAR_REQUEST = "@impressora/SALVAR_REQUEST";
export const IMPRESSORA_SALVAR_SUCCESS = "@impressora/SALVAR_SUCCESS";
export const IMPRESSORA_EDITAR_REQUEST = "@impressora/EDITAR_REQUEST";
export const IMPRESSORA_EDITAR_SUCCESS = "@impressora/EDITAR_SUCCESS";
export const IMPRESSORA_DELETE_REQUEST = "@impressora/DELETE_REQUEST";
export const IMPRESSORA_DELETE_SUCCESS = "@impressora/DELETE_SUCCESS";
export const IMPRESSORA_ERROR = "@impressora/ERROR";

//DASHBOARD PRODUCAO
export const DASHBOARD_PRODUCAO_LIST_REQUEST = "@dashboardProducao/LIST_REQUEST";
export const DASHBOARD_PRODUCAO_LIST_SUCCESS = "@dashboardProducao/LIST_SUCCESS";
export const DASHBOARD_PRODUCAO_INDICADORES_REQUEST = "@dashboardProducao/INDICADORES_REQUEST";
export const DASHBOARD_PRODUCAO_INDICADORES_SUCCESS = "@dashboardProducao/INDICADORES_SUCCESS";
export const DASHBOARD_PRODUCAO_STATUS_SERIAIS_REQUEST = "@dashboardProducao/STATUS_SERIAIS_REQUEST";
export const DASHBOARD_PRODUCAO_STATUS_SERIAIS_SUCCESS = "@dashboardProducao/STATUS_SERIAIS_SUCCESS";
export const DASHBOARD_PRODUCAO_SERIAIS_DIA_REQUEST = "@dashboardProducao/SERIAIS_DIA_REQUEST";
export const DASHBOARD_PRODUCAO_SERIAIS_DIA_SUCCESS = "@dashboardProducao/SERIAIS_DIA_SUCCESS";
export const DASHBOARD_PRODUCAO_ERROR = "@dashboardProducao/ERROR";

//CLASSE POR PLANEJADOR
export const CLASSE_POR_PLANEJADOR_LIST_REQUEST = "@classePorPlanejador/LIST_REQUEST";
export const CLASSE_POR_PLANEJADOR_LIST_SUCCESS = "@classePorPlanejador/LIST_SUCCESS";
export const CLASSE_POR_PLANEJADOR_PREPARAR_NOVO_REQUEST = "@classePorPlanejador/PREPARAR_NOVO_REQUEST";
export const CLASSE_POR_PLANEJADOR_PREPARAR_NOVO_SUCCESS = "@classePorPlanejador/PREPARAR_NOVO_SUCCESS";
export const CLASSE_POR_PLANEJADOR_PREPARAR_EDITAR_REQUEST = "@classePorPlanejador/PREPARAR_EDITAR_REQUEST";
export const CLASSE_POR_PLANEJADOR_PREPARAR_EDITAR_SUCCESS = "@classePorPlanejador/PREPARAR_EDITAR_SUCCESS";
export const CLASSE_POR_PLANEJADOR_SALVAR_REQUEST = "@classePorPlanejador/SALVAR_REQUEST";
export const CLASSE_POR_PLANEJADOR_SALVAR_SUCCESS = "@classePorPlanejador/SALVAR_SUCCESS";
export const CLASSE_POR_PLANEJADOR_EDITAR_REQUEST = "@classePorPlanejador/EDITAR_REQUEST";
export const CLASSE_POR_PLANEJADOR_EDITAR_SUCCESS = "@classePorPlanejador/EDITAR_SUCCESS";
export const CLASSE_POR_PLANEJADOR_DELETE_REQUEST = "@classePorPlanejador/DELETE_REQUEST";
export const CLASSE_POR_PLANEJADOR_DELETE_SUCCESS = "@classePorPlanejador/DELETE_SUCCESS";
export const CLASSE_POR_PLANEJADOR_ERROR = "@classePorPlanejador/ERROR";

//PREFIXO PRODUCAO FORNECEDOR
export const PREFIXO_PRODUCAO_FORNECEDOR_LIST_REQUEST = "@prefixoProducaoFornecedor/LIST_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_LIST_SUCCESS = "@prefixoProducaoFornecedor/LIST_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_PREPARAR_NOVO_REQUEST = "@prefixoProducaoFornecedor/PREPARAR_NOVO_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_PREPARAR_NOVO_SUCCESS = "@prefixoProducaoFornecedor/PREPARAR_NOVO_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_PREPARAR_EDITAR_REQUEST = "@prefixoProducaoFornecedor/PREPARAR_EDITAR_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_PREPARAR_EDITAR_SUCCESS = "@prefixoProducaoFornecedor/PREPARAR_EDITAR_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_SALVAR_REQUEST = "@prefixoProducaoFornecedor/SALVAR_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_SALVAR_SUCCESS = "@prefixoProducaoFornecedor/SALVAR_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_EDITAR_REQUEST = "@prefixoProducaoFornecedor/EDITAR_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_EDITAR_SUCCESS = "@prefixoProducaoFornecedor/EDITAR_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_DELETE_REQUEST = "@prefixoProducaoFornecedor/DELETE_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_DELETE_SUCCESS = "@prefixoProducaoFornecedor/DELETE_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_UPDATE_VALOR_REQUEST = "@prefixoProducaoFornecedor/UPDATE_VALOR_REQUEST";
export const PREFIXO_PRODUCAO_FORNECEDOR_UPDATE_VALOR_SUCCESS = "@prefixoProducaoFornecedor/UPDATE_VALOR_SUCCESS";
export const PREFIXO_PRODUCAO_FORNECEDOR_ERROR = "@prefixoProducaoFornecedor/ERROR";

// CONFIGURACAO GERAL
export const CONF_GERAL_LIST_REQUEST = "@confGeral/LIST_REQUEST";
export const CONF_GERAL_LIST_SUCCESS = "@confGeral/LIST_SUCCESS";
export const CONF_GERAL_UPDATE_VALOR_REQUEST =
  "@confGeral/UPDATE_VALOR_REQUEST";
export const CONF_GERAL_UPDATE_VALOR_SUCCESS =
  "@confGeral/UPDATE_VALOR_SUCCESS";
export const CONF_GERAL_ERROR = "@confGeral/ERROR";

//GRUPO RECURSO
export const GRUPO_RECURSO_LIST_REQUEST = "@grupoRecurso/LIST_REQUEST";
export const GRUPO_RECURSO_LIST_SUCCESS = "@grupoRecurso/LIST_SUCCESS";
export const GRUPO_RECURSO_SALVAR_REQUEST = "@grupoRecurso/SALVAR_REQUEST";
export const GRUPO_RECURSO_SALVAR_SUCCESS = "@grupoRecurso/SALVAR_SUCCESS";
export const GRUPO_RECURSO_EDITAR_REQUEST = "@grupoRecurso/EDITAR_REQUEST";
export const GRUPO_RECURSO_EDITAR_SUCCESS = "@grupoRecurso/EDITAR_SUCCESS";
export const GRUPO_RECURSO_DELETAR_REQUEST = "@grupoRecurso/DELETAR_REQUEST";
export const GRUPO_RECURSO_DELETAR_SUCCESS = "@grupoRecurso/DELETAR_SUCCESS";
export const GRUPO_RECURSO_PREPARAR_NOVO_REQUEST = "@grupoRecurso/PREPARAR_NOVO_REQUEST";
export const GRUPO_RECURSO_PREPARAR_NOVO_SUCCESS = "@grupoRecurso/PREPARAR_NOVO_SUCCESS";
export const GRUPO_RECURSO_PREPARAR_EDITAR_REQUEST = "@grupoRecurso/PREPARAR_EDITAR_REQUEST";
export const GRUPO_RECURSO_PREPARAR_EDITAR_SUCCESS = "@grupoRecurso/PREPARAR_EDITAR_SUCCESS";
export const GRUPO_RECURSO_ATIVAR_OU_DESATIVAR_REQUEST = "@grupoRecurso/ATIVAR_DESATIVAR_REQUEST";
export const GRUPO_RECURSO_ERROR = "@grupoRecurso/ERROR";

//REQUEST MANAGER
export const START_REQUEST = "START_REQUEST";
export const FINISH_REQUEST = "FINISH_REQUEST";


// CONECTOR
export const CONECTOR_SALVAR_REQUEST = "@conector/SALVAR_REQUEST";
export const CONECTOR_SALVAR_SUCCESS = "@conector/SALVAR_SUCCESS";
export const CONECTOR_LIST_REQUEST = "@conector/LIST_REQUEST";
export const CONECTOR_LIST_SUCCESS = "@conector/LIST_SUCCESS";
export const CONECTOR_DELETE_REQUEST = "@conector/DELETE_REQUEST";
export const CONECTOR_SET_ENTITY = "@conector/SET_ENTITY";
export const CONECTOR_DELETE_SUCCESS = "@conector/DELETE_SUCCESS";
export const CONECTOR_EDITAR_REQUEST = "@conector/EDITAR_REQUEST";
export const CONECTOR_EDITAR_SUCCESS = "@conector/EDITAR_SUCCESS";
export const CONECTOR_PREPARAR_EDITAR_REQUEST = "@conector/PREPARAR_EDITAR_REQUEST";
export const CONECTOR_PREPARAR_EDITAR_SUCCESS = "@conector/PREPARAR_EDITAR_SUCCESS";
export const CONECTOR_PREPARAR_NOVO_REQUEST = "@conector/PREPARAR_NOVO_REQUEST";
export const CONECTOR_PREPARAR_NOVO_SUCCESS = "@conector/PREPARAR_NOVO_SUCCESS";
export const CONECTOR_ERROR = "@conector/CONECTOR_ERROR";

//ACESSO
export const ACESSO_SALVAR_REQUEST = "@acesso/SALVAR_REQUEST";
export const ACESSO_SALVAR_SUCCESS = "@acesso/SALVAR_SUCCESS";
export const ACESSO_LIST_REQUEST = "@acesso/LIST_REQUEST";
export const ACESSO_LIST_SUCCESS = "@acesso/LIST_SUCCESS";
export const ACESSO_DELETE_REQUEST = "@acesso/DELETE_REQUEST";
export const ACESSO_DELETE_SUCCESS = "@acesso/DELETE_SUCCESS";
export const ACESSO_EDITAR_REQUEST = "@acesso/EDITAR_REQUEST";
export const ACESSO_EDITAR_SUCCESS = "@acesso/EDITAR_SUCCESS";
export const ACESSO_PREPARAR_EDITAR_REQUEST = "@acesso/PREPARAR_EDITAR_REQUEST";
export const ACESSO_PREPARAR_EDITAR_SUCCESS = "@acesso/PREPARAR_EDITAR_SUCCESS";
export const ACESSO_PREPARAR_NOVO_REQUEST = "@acesso/PREPARAR_NOVO_REQUEST";
export const ACESSO_PREPARAR_NOVO_SUCCESS = "@acesso/PREPARAR_NOVO_SUCCESS";
export const ACESSO_ERROR = "@acesso/ACESSO_ERROR";
export const ACESSO_FILTRAR_FORNECEDOR = "@acesso/FILTRAR_FORNECEDOR";

//LINHA DE PRODUÇÃO
export const LINHA_DE_PRODUCAO_SALVAR_REQUEST = "@linhaDeProducao/SALVAR_REQUEST";
export const LINHA_DE_PRODUCAO_SALVAR_SUCCESS = "@linhaDeProducao/SALVAR_SUCCESS";
export const LINHA_DE_PRODUCAO_LIST_REQUEST = "@linhaDeProducao/LIST_REQUEST";
export const LINHA_DE_PRODUCAO_LIST_SUCCESS = "@linhaDeProducao/LIST_SUCCESS";
export const LINHA_DE_PRODUCAO_DELETE_REQUEST = "@linhaDeProducao/DELETE_REQUEST";
export const LINHA_DE_PRODUCAO_DELETE_SUCCESS = "@linhaDeProducao/DELETE_SUCCESS";
export const LINHA_DE_PRODUCAO_EDITAR_REQUEST = "@linhaDeProducao/EDITAR_REQUEST";
export const LINHA_DE_PRODUCAO_EDITAR_SUCCESS = "@linhaDeProducao/EDITAR_SUCCESS";
export const LINHA_DE_PRODUCAO_PREPARAR_NOVO_REQUEST = "@linhaDeProducao/PREPARAR_NOVO_REQUEST";
export const LINHA_DE_PRODUCAO_PREPARAR_NOVO_SUCCESS = "@linhaDeProducao/PREPARAR_NOVO_SUCCESS";
export const LINHA_DE_PRODUCAO_PREPARAR_EDITAR_REQUEST = "@linhaDeProducao/PREPARAR_EDITAR_REQUEST";
export const LINHA_DE_PRODUCAO_PREPARAR_EDITAR_SUCCESS = "@linhaDeProducao/PREPARAR_EDITAR_SUCCESS";
export const LINHA_DE_PRODUCAO_BUSCAR_POR_NOME_REQUEST = "@linhaDeProducao/BUSCAR_POR_NOME_REQUEST";
export const LINHA_DE_PRODUCAO_BUSCAR_POR_NOME_SUCCESS = "@linhaDeProducao/BUSCAR_POR_NOME_SUCCESS";
export const LINHA_DE_PRODUCAO_RESTAURAR_REQUEST = "@linhaDeProducao/RESTAURAR_REQUEST";
export const LINHA_DE_PRODUCAO_RESTAURAR_SUCCESS = "@linhaDeProducao/RESTAURAR_SUCCESS";
export const LINHA_DE_PRODUCAO_ATIVAR_OU_DESATIVAR_REQUEST = "@linhaDeProducao/ATIVAR_OU_DESATIVAR_REQUEST";
export const LINHA_DE_PRODUCAO_ERROR = "@linhaDeProducao/LINHA_DE_PRODUCAO_ERROR";

//GRUPO LINHA DE PRODUCAO
export const GRUPO_LINHA_PRODUCAO_LIST_REQUEST = "@grupoLinhaDeProducao/LIST_REQUEST";
export const GRUPO_LINHA_PRODUCAO_LIST_SUCCESS = "@grupoLinhaDeProducao/LIST_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_SALVAR_REQUEST = "@grupoLinhaDeProducao/SALVAR_REQUEST";
export const GRUPO_LINHA_PRODUCAO_SALVAR_SUCCESS = "@grupoLinhaDeProducao/SALVAR_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_EDITAR_REQUEST = "@grupoLinhaDeProducao/EDITAR_REQUEST";
export const GRUPO_LINHA_PRODUCAO_EDITAR_SUCCESS = "@grupoLinhaDeProducao/EDITAR_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_DELETE_REQUEST = "@grupoLinhaDeProducao/DELETE_REQUEST";
export const GRUPO_LINHA_PRODUCAO_DELETE_SUCCESS = "@grupoLinhaDeProducao/DELETE_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_PREPARAR_EDITAR_REQUEST = "@grupoLinhaDeProducao/PREPARAR_EDITAR_REQUEST";
export const GRUPO_LINHA_PRODUCAO_PREPARAR_EDITAR_SUCCESS = "@grupoLinhaDeProducao/PREPARAR_EDITAR_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_PREPARAR_NOVO_REQUEST = "@grupoLinhaDeProducao/PREPARAR_NOVO_REQUEST";
export const GRUPO_LINHA_PRODUCAO_PREPARAR_NOVO_SUCCESS = "@grupoLinhaDeProducao/PREPARAR_NOVO_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_SET_ENTITY = "@grupoLinhaDeProducao/SET_ENTITY";
export const GRUPO_LINHA_PRODUCAO_ATIVAR_OU_DESATIVAR_REQUEST = "@grupoLinhaDeProducao/ATIVAR_DESATIVAR_REQUEST";
export const GRUPO_LINHA_PRODUCAO_EXPORTAR_REQUEST = "@grupoLinhaDeProducao/EXPORTAR_REQUEST";
export const GRUPO_LINHA_PRODUCAO_EXPORTAR_SUCCESS = "@grupoLinhaDeProducao/EXPORTAR_SUCCESS";
export const GRUPO_LINHA_PRODUCAO_ERROR = "@grupoLinhaDeProducao/ERROR";

//DEFEITO
export const DEFEITO_SALVAR_REQUEST = "@defeito/SALVAR_REQUEST";
export const DEFEITO_SALVAR_SUCCESS = "@defeito/SALVAR_SUCCESS";
export const DEFEITO_LIST_REQUEST = "@defeito/LIST_REQUEST";
export const DEFEITO_LIST_SUCCESS = "@defeito/LIST_SUCCESS";
export const DEFEITO_DELETE_REQUEST = "@defeito/DELETE_REQUEST";
export const DEFEITO_DELETE_SUCCESS = "@defeito/DELETE_SUCCESS";
export const DEFEITO_EDITAR_REQUEST = "@defeito/EDITAR_REQUEST";
export const DEFEITO_EDITAR_SUCCESS = "@defeito/EDITAR_SUCCESS";
export const DEFEITO_PREPARAR_EDITAR_REQUEST = "@defeito/PREPARAR_EDITAR_REQUEST";
export const DEFEITO_PREPARAR_EDITAR_SUCCESS = "@defeito/PREPARAR_EDITAR_SUCCESS";
export const DEFEITO_PREPARAR_NOVO_REQUEST = "@defeito/PREPARAR_NOVO_REQUEST";
export const DEFEITO_PREPARAR_NOVO_SUCCESS = "@defeito/PREPARAR_NOVO_SUCCESS";
export const DEFEITO_ATIVAR_OU_DESATIVAR_REQUEST = "@defeito/ATIVAR_DESATIVAR_REQUEST";
export const DEFEITO_ERROR = "@defeito/ERROR";

//PRODUTO ETIQUETA
export const PRODUTO_ETIQUETA_SALVAR_REQUEST = "@produtoEtiqueta/SALVAR_REQUEST";
export const PRODUTO_ETIQUETA_SALVAR_SUCCESS = "@produtoEtiqueta/SALVAR_SUCCESS";
export const PRODUTO_ETIQUETA_LIST_REQUEST = "@produtoEtiqueta/LIST_REQUEST";
export const PRODUTO_ETIQUETA_LIST_SUCCESS = "@produtoEtiqueta/LIST_SUCCESS";
export const PRODUTO_ETIQUETA_DELETE_REQUEST = "@produtoEtiqueta/DELETE_REQUEST";
export const PRODUTO_ETIQUETA_DELETE_SUCCEESS = "@produtoEtiqueta/DELETE_SUCCESS";
export const PRODUTO_ETIQUETA_EDITAR_REQUEST = "@produtoEtiqueta/EDITAR_REQUEST";
export const PRODUTO_ETIQUETA_EDITAR_SUCCESS = "@produtoEtiqueta/EDITAR_SUCCESS";
export const PRODUTO_ETIQUETA_PREPARAR_EDITAR_REQUEST = "@produtoEtiqueta/PREPARAR_EDITAR_REQUEST";
export const PRODUTO_ETIQUETA_PREPARAR_EDITAR_SUCCESS = "@produtoEtiqueta/PREPARAR_EDITAR_SUCCESS";
export const PRODUTO_ETIQUETA_PREPARAR_NOVO_REQUEST = "@produtoEtiqueta/PREPARAR_NOVO_REQUEST";
export const PRODUTO_ETIQUETA_PREPARAR_NOVO_SUCCESS = "@produtoEtiqueta/PREPARAR_NOVO_SUCCESS";
export const PRODUTO_ETIQUETA_GERAR_ETIQUETA_REQUEST = "@produtoEtiqueta/GERAR_ETIQUETA_REQUEST";
export const PRODUTO_ETIQUETA_GERAR_ETIQUETA_SUCCESS = "@produtoEtiqueta/GERAR_ETIQUETA_SUCCESS";
export const PRODUTO_ETIQUETA_ERROR = "@produtoEtiqueta/ERROR";


//GERACAO ORDEM DE PRODUCAO
export const GERACAO_ORDEM_DE_PRODUCAO_SET_ENTITY = "@geracaoOrdemDeProducao/SET_ENTITY";
export const GERACAO_ORDEM_DE_PRODUCAO_LIMPAR_PRODUTOS = "@geracaoOrdemDeProducao/LIMPAR_PRODUTOS";
export const GERACAO_ORDEM_DE_PRODUCAO_GERAR_REQUEST = "@geracaoOrdemDeProducao/GERAR_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_GERAR_SUCCESS = "@geracaoOrdemDeProducao/GERAR_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_PRODUTOS_REQUEST = "@geracaoOrdemDeProducao/BUSCAR_PRODUTOS_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_PRODUTOS_SUCCESS = "@geracaoOrdemDeProducao/BUSCAR_PRODUTOS_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_FORNECEDORES_LISTAS_ROTEIROS_REQUEST = "@geracaoOrdemDeProducao/BUSCAR_FORNECEDORES_LISTAS_ROTEIROS_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_FORNECEDORES_LISTAS_ROTEIROS_SUCCESS = "@geracaoOrdemDeProducao/BUSCAR_FORNECEDORES_LISTAS_ROTEIROS_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_POR_OV_REQUEST = "@geracaoOrdemDeProducao/BUSCAR_POR_OV_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_BUSCAR_POR_OV_SUCCESS = "@geracaoOrdemDeProducao/BUSCAR_POR_OV_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_ORDENS_REQUEST = "@geracaoOrdemDeProducao/SELECIONAR_ORDENS_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_ORDENS_SUCCESS = "@geracaoOrdemDeProducao/SELECIONAR_ORDENS_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_LISTA_ROTEIRO_REQUEST = "@geracaoOrdemDeProducao/SELECIONAR_LISTA_ROTEIRO_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_LISTA_ROTEIRO_SUCCESS = "@geracaoOrdemDeProducao/SELECIONAR_LISTA_ROTEIRO_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_DATA_REQUEST = "@geracaoOrdemDeProducao/SELECIONAR_DATA_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_DATA_SUCCESS = "@geracaoOrdemDeProducao/SELECIONAR_DATA_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_JUSTIFICATIVA_REQUEST = "@geracaoOrdemDeProducao/SELECIONAR_JUSTIFICATIVA_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_SELECIONAR_JUSTIFICATIVA_SUCCESS = "@geracaoOrdemDeProducao/SELECIONAR_JUSTIFICATIVA_SUCCESS";
export const GERACAO_ORDEM_DE_PRODUCAO_IMPORTAR_ORDENS_REQUEST = "@geracaoOrdemDeProducao/IMPORTAR_ORDENS_REQUEST";
export const GERACAO_ORDEM_DE_PRODUCAO_IMPORTAR_ORDENS_SUCCESS = "@geracaoOrdemDeProducao/IMPORTAR_ORDENS_SUCCESS";
export const GERACAO_DE_ORDEM_DE_PRODUCAO_USER_FORNECEDORES_REQUEST = "@geracaoOrdemDeProducao/USER_FORNECEDORES_REQUEST"
export const GERACAO_DE_ORDEM_DE_PRODUCAO_USER_FORNECEDORES_SUCCESS = "@geracaoOrdemDeProducao/USER_FORNECEDORES_SUCCESS"
export const GERACAO_ORDEM_DE_PRODUCAO_ERROR = "@geracaoOrdemDeProducao/ERROR";

// APONTAMENTO
export const APONTAMENTO_SALVAR_REQUEST = "@apontamento/SALVAR_REQUEST";
export const APONTAMENTO_SALVAR_SUCCESS = "@apontamento/SALVAR_SUCCESS";
export const APONTAMENTO_GERAR_ETIQUETA_REQUEST = "@apontamento/GERAR_ETIQUETA_REQUEST";
export const APONTAMENTO_GERAR_ETIQUETA_SUCCESS = "@apontamento/GERAR_ETIQUETA_SUCCESS";
export const APONTAMENTO_VALIDAR_SERIAL_REQUEST = "@apontamento/VALIDAR_SERIAL_REQUEST";
export const APONTAMENTO_VALIDAR_SERIAL_SUCCESS = "@apontamento/VALIDAR_SERIAL_SUCCESS";
export const APONTAMENTO_VERIFICAR_PARADA_REQUEST = "@apontamento/VERIFICAR_PARADA_REQUEST";
export const APONTAMENTO_VERIFICAR_PARADA_SUCCESS = "@apontamento/VERIFICAR_PARADA_SUCCESS";
export const APONTAMENTO_SET_MOTIVO_REQUEST = "@apontamento/SET_MOTIVO_REQUEST";
export const APONTAMENTO_SET_MOTIVO_SUCCESS = "@apontamento/SET_MOTIVO_SUCCESS";
export const APONTAMENTO_PARAR_RECURSO_REQUEST = "@apontamento/PARAR_RECURSO_REQUEST";
export const APONTAMENTO_PARAR_RECURSO_SUCCESS = "@apontamento/PARAR_RECURSO_SUCCESS";
export const FECHAR_MODAL = "@apontamento/FECHAR_MODAL";
export const GET_RECURSOS_REQUEST = "@apontamento/GET_RECURSOS_REQUEST";
export const GET_RECURSOS_SUCCESS = "@apontamento/GET_RECURSOS_SUCCESS";
export const GET_DADOSAPONTAMENTOPORRECURSO_REQUEST = "@apontamento/GET_DADOSAPONTAMENTOPORRECURSO_REQUEST";
export const GET_DADOSAPONTAMENTOPORRECURSO_SUCCESS = "@apontamento/GET_DADOSAPONTAMENTOPORRECURSO_SUCCESS";
export const VERIFICAR_USUARIO_REQUEST = "@apontamento/VERIFICAR_USUARIO_REQUEST";
export const VERIFICAR_USUARIO_SUCCESS = "@apontamento/VERIFICAR_USUARIO_SUCCESS";
export const APONTAMENTO_VALIDAR_OF_REQUEST = "@apontamento/VALIDAR_OF_REQUEST";
export const APONTAMENTO_VALIDAR_OF_SUCCESS = "@apontamento/VALIDAR_OF_SUCCESS";
export const APONTAMENTO_ERROR = "@apontamento/ERROR";
export const LIMPAR_TABELA = "@apontamento/LIMPAR_TABELA";

//SEQUENCIAMENTO
export const SEQUENCIAMENTO_BUSCAR_CATALOGO_DO_PRODUTO_REQUEST = "@sequenciamento/BUSCAR_CATALOGO_DO_PRODUTO_REQUEST";
export const SEQUENCIAMENTO_BUSCAR_CATALOGO_DO_PRODUTO_SUCCESS = "@sequenciamento/BUSCAR_CATALOGO_DO_PRODUTO_SUCCESS";
export const SEQUENCIAMENTO_BUSCAR_GRUPOS_REQUEST = "@sequenciamento/BUSCAR_GRUPOS_REQUEST";
export const SEQUENCIAMENTO_BUSCAR_GRUPOS_SUCCESS = "@sequenciamento/BUSCAR_GRUPOS_SUCCESS";
export const SEQUENCIAMENTO_BUSCAR_LINHAS_GRUPO_REQUEST = "@sequenciamento/BUSCAR_LINHAS_GRUPO_REQUEST";
export const SEQUENCIAMENTO_BUSCAR_LINHAS_GRUPO_SUCCESS = "@sequenciamento/BUSCAR_LINHAS_GRUPO_SUCCESS";
export const SEQUENCIAMENTO_BUSCAR_ORDENS_GRUPO_REQUEST = "@sequenciamento/BUSCAR_ORDENS_GRUPO_REQUEST";
export const SEQUENCIAMENTO_BUSCAR_ORDENS_GRUPO_SUCCESS = "@sequenciamento/BUSCAR_ORDENS_GRUPO_SUCCESS";
export const SEQUENCIAMENTO_SALVAR_REQUEST = "@sequenciamento/SALVAR_REQUEST";
export const SEQUENCIAMENTO_ALTERAR_ORDEM_REQUEST = "@sequenciamento/ALTERAR_ORDEM_REQUEST";
export const SEQUENCIAMENTO_ALTERAR_ORDEM_SUCCESS = "@sequenciamento/ALTERAR_ORDEM_SUCCESS";
export const SEQUENCIAMENTO_EXCLUIR_REQUEST = "@sequenciamento/EXCLUIR_REQUEST";
export const SEQUENCIAMENTO_SET_PRODUTO_SELECIONADO = "@sequenciamento/SET_PRODUTO_SELECIONADO";
export const SEQUENCIAMENTO_SET_GRUPO_SELECIONADO = "@sequenciamento/SET_GRUPO_SELECIONADO";
export const SEQUENCIAMENTO_CANCELA_DROP = "@sequenciamento/CANCELA_DROP";
export const SEQUENCIAMENTO_HIDE_MODAL_CATALOGO = "@sequenciamento/HIDE_MODAL_CATALOGO";
export const SEQUENCIAMENTO_SET_ORDEM_POS_ANTERIOR = "@sequenciamento/SET_ORDEM_POS_ANTERIOR";
export const SEQUENCIAMENTO_ASSOCIAR_PRODUTO_AO_GRUPO_REQUEST = "@sequenciamento/ASSOCIAR_PRODUTO_AO_GRUPO_REQUEST";
export const SEQUENCIAMENTO_TOTAL_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_REQUEST = "@sequenciamento/TOTAL_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_REQUEST";
export const SEQUENCIAMENTO_TOTAL_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_SUCCESS = "@sequenciamento/TOTAL_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_SUCCESS";
export const SEQUENCIAMENTO_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_REQUEST = "@sequenciamento/OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_REQUEST";
export const SEQUENCIAMENTO_OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_SUCCESS = "@sequenciamento/OP_PRODUTOS_SEM_GRUPO_ASSOCIADO_SUCCESS";
export const SEQUENCIAMENTO_OP_PRODUTOS_ASSOCIADO_GRUPO_REQUEST = "@sequenciamento/OP_PRODUTOS_ASSOCIADO_GRUPO_REQUEST";
export const SEQUENCIAMENTO_OP_PRODUTOS_ASSOCIADO_GRUPO_SUCCESS = "@sequenciamento/OP_PRODUTOS_ASSOCIADO_GRUPO_SUCCESS";
export const SEQUENCIAMENTO_GET_MATERIA_PRIMA_ORDEM_PRODUCAO_REQUEST = "@sequenciamento/GET_MATERIA_PRIMA_ORDEM_PRODUCAO_REQUEST";
export const SEQUENCIAMENTO_GET_MATERIA_PRIMA_ORDEM_PRODUCAO_SUCCESS = "@sequenciamento/GET_MATERIA_PRIMA_ORDEM_PRODUCAO_SUCCESS";
export const SEQUENCIAMENTO_ORDENACAO_RAPIDA_REQUEST = "@sequenciamento/ORDENACAO_RAPIDA_REQUEST";
export const SEQUENCIAMENTO_ORDENACAO_RAPIDA_SUCCESS = "@sequenciamento/ORDENACAO_RAPIDA_SUCCESS";
export const SEQUENCIAMENTO_ALTERAR_LDP_REQUEST = "@sequenciamento/ALTERAR_LDP_REQUEST";
export const SEQUENCIAMENTO_ALTERAR_LDP_SUCCESS = "@sequenciamento/ALTERAR_LDP_SUCCESS";
export const SEQUENCIAMENTO_MUDAR_ORDEM_REQUEST = "@sequenciamento/MUDAR_ORDEM_REQUEST";
export const SEQUENCIAMENTO_MUDAR_ORDEM_SUCCESS = "@sequenciamento/MUDAR_ORDEM_SUCCESS";
export const SEQUENCIAMENTO_ERROR = "@sequenciamento/ERROR";

//APOIO
export const APOIO_BUSCAR_GRUPOS_LINHAS_REQUEST = "@apoio/BUSCAR_GRUPOS_LINHAS_REQUEST";
export const APOIO_BUSCAR_GRUPOS_LINHAS_SUCCESS = "@apoio/BUSCAR_GRUPOS_LINHAS_SUCCESS";
export const APOIO_BUSCAR_GRUPO_LINHAS_REQUEST = "@apoio/BUSCAR_GRUPO_LINHAS_REQUEST";
export const APOIO_BUSCAR_GRUPO_LINHAS_SUCCESS = "@apoio/BUSCAR_GRUPO_LINHAS_SUCCESS";
export const APOIO_BUSCAR_SERIAL_REQUEST = "@apoio/BUSCAR_SERIAL_REQUEST";
export const APOIO_BUSCAR_SERIAL_SUCCESS = "@apoio/BUSCAR_SERIAL_SUCCESS";
export const APOIO_REDIRECIONAR_SERIAL_REQUEST = "@apoio/REDIRECIONAR_SERIAL_REQUEST";
export const APOIO_DESCARTAR_SERIAL_REQUEST = "@apoio/DELETAR_SERIAL_REQUEST";

//SERIAL
export const SERIAL_LIST_REQUEST = "@serial/LIST_REQUEST";
export const SERIAL_LIST_SUCCESS = "@serial/LIST_SUCCESS";
export const SERIAL_VALORES_INICIAIS_REQUEST = "@serial/VALORES_INICIAIS_REQUEST";
export const SERIAL_VALORES_INICIAIS_SUCCESS = "@serial/VALORES_INICIAIS_SUCCESS";
export const SERIAL_LIST_HISTORICO_REQUEST = "@serial/LIST_HISTORICO_REQUEST";
export const SERIAL_LIST_HISTORICO_SUCCESS = "@serial/LIST_HISTORICO_SUCCESS";
export const SERIAL_GERAR_ETIQUETA_REQUEST = "@serial/GERAR_ETIQUETA_REQUEST";
export const SERIAL_GERAR_ETIQUETA_SUCCESS = "@serial/GERAR_ETIQUETA_SUCCESS";
export const SERIAL_IMPRIMIR_REQUEST = "@serial/IMPRIMIR_REQUEST";
export const SERIAL_IMPRIMIR_SUCCESS = "@serial/IMPRIMIR_SUCCESS";
export const SERIAL_ESTORNAR_APONTAMENTO_REQUEST = "@serial/ESTORNAR_APONTAMENTO_REQUEST";
export const SERIAL_ESTORNAR_APONTAMENTO_SUCCESS = "@serial/ESTORNAR_APONTAMENTO_SUCCESS";
export const SERIAL_EXPORTAR_REQUEST = "@serial/EXPORTAR_REQUEST";
export const SERIAL_EXPORTAR_SUCCESS = "@serial/EXPORTAR_SUCCESS";
export const SERIAL_SUCATEAR_REQUEST = "@serial/SUCATEAR_REQUEST";
export const SERIAL_SUCATEAR_SUCCESS = "@serial/SUCATEAR_SUCCESS";
export const SERIAL_FOLHA_IMPRESSAO_DATA_REQUEST = "@serial/FOLHA_IMPRESSAO_DATA_REQUEST"
export const SERIAL_FOLHA_IMPRESSAO_DATA_SUCCESS = "@serial/FOLHA_IMPRESSAO_DATA_SUCCESS"
export const SERIAL_ERROR = "@serial/ERROR";


// MENUITEM
export const MENU_ITEM_REQUEST = "@menuItem/LISTAR_REQUEST";
export const MENU_SET_URL_PATH = "@menuItem/SET_URL_PATH";
export const MENU_ITEM_SALVAR_SUCCESS = "@menuItem/SALVAR_SUCCESS";
export const MENU_ITEM_ERROR = "@menuItem/CONECTOR_ERROR";

//ACOMPANHAMENTO ORDEM DE PRODUÇÃO
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_LIST_REQUEST = "@acompanhamentoOrdemDeProducao/LIST_RESQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_LIST_SUCCESS = "@acompanhamentoOrdemDeProducao/LIST_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_REEXPORTAR_REQUEST = "@acompanhamentoOrdemDeProducao/REEXPORTAR_REQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_REEXPORTAR_SUCCESS = "@acompanhamentoOrdemDeProducao/REEXPORTAR_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ATUALIZAR_REQUEST = "@acompanhamentoOrdemDeProducao/ATUALIZAR_REQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ATUALIZAR_SUCCESS = "@acompanhamentoOrdemDeProducao/ATUALIZAR_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_EXPORTAR_REQUEST = "@acompanhamentoOrdemDeProducao/EXPORTAR_REQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_EXPORTAR_SUCCESS = "@acompanhamentoOrdemDeProducao/EXPORTAR_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_ATRASADAS_REQUEST = "@acompanhamentoOrdemDeProducao/ORDENS_ATRASADAS_REQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_ATRASADAS_SUCCESS = "@acompanhamentoOrdemDeProducao/ORDENS_ATRASADAS_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_PREPARE_EDIT_REQUEST = "@acompanhamentoOrdemDeProducao/prepareEditRequest"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_PREPARE_EDIT_SUCCESS = "@acompanhamentoOrdemDeProducao/prepareEditSuccess"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_EDIT_REQUEST = "@acompanhamentoOrdemDeProducao/editRequest"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ORDENS_EDIT_SUCCESS = "@acompanhamentoOrdemDeProducao/editSuccess"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ALTERAR_EM_MASSA_REQUEST = "@acompanhamentoOrdemDeProducao/ALTERAR_EM_MASSA_REQUEST"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ALTERAR_EM_MASSA_SUCCESS = "@acompanhamentoOrdemDeProducao/ALTERAR_EM_MASSA_SUCCESS"
export const ACOMPANHAMENTO_ORDEM_DE_PRODUCAO_ERROR = "@acompanhamentoOrdemDeProducao/ERROR"

//ACOMPANHAMENTO ORDEM DE PRODUÇÃO
export const FATURAMENTO_LIST_REQUEST = "@faturamento/LIST_RESQUEST"
export const FATURAMENTO_LIST_SUCCESS = "@faturamento/LIST_SUCCESS"
export const FATURAMENTO_ENVIO_LOTE_ROMANEIO_REQUEST = "@faturamento/ENVIO_LOTE_ROMANEIO_RESQUEST"
export const FATURAMENTO_ENVIO_LOTE_ROMANEIO_SUCCESS = "@faturamento/ENVIO_LOTE_ROMANEIO_SUCCESS"
export const FATURAMENTO_CHECAR_LOTE_ROMANEIO_REQUEST = "@faturamento/CHECAR_LOTE_ROMANEIO_RESQUEST"
export const FATURAMENTO_CHECAR_LOTE_ROMANEIO_SUCCESS = "@faturamento/CHECAR_LOTE_ROMANEIO_SUCCESS"
export const FATURAMENTO_FECHAR_LOTE_INCOMPLETO_REQUEST = "@faturamento/FECHAR_LOTE_INCOMPLETO_RESQUEST"
export const FATURAMENTO_FECHAR_LOTE_INCOMPLETO_SUCCESS = "@faturamento/FECHAR_LOTE_INCOMPLETO_SUCCESS"
export const FATURAMENTO_EXPORTAR_LOTES_REQUEST = "@faturamento/EXPORTAR_LOTES_REQUEST"
export const FATURAMENTO_EXPORTAR_LOTES_SUCCESS = "@faturamento/EXPORTAR_LOTES_SUCCESS"
export const FATURAMENTO_LIST_IMPRESSORAS_REQUEST = "@faturamento/LIST_IMPRESSORAS_REQUEST"
export const FATURAMENTO_LIST_IMPRESSORAS_SUCCESS = "@faturamento/LIST_IMPRESSORAS_SUCCESS"
export const FATURAMENTO_GET_CAIXAS_REQUEST = "@faturamento/GET_CAIXAS_REQUEST"
export const FATURAMENTO_GET_CAIXAS_SUCCESS = "@faturamento/GET_CAIXAS_SUCCESS"
export const FATURAMENTO_EXPORTAR_CAIXAS_REQUEST = "@faturamento/EXPORTAR_CAIXAS_REQUEST"
export const FATURAMENTO_EXPORTAR_CAIXAS_SUCCESS = "@faturamento/EXPORTAR_CAIXAS_SUCCESS"
export const FATURAMENTO_ABRIR_LOTE_REQUEST = "@faturamento/ABRIR_LOTE_REQUEST"
export const FATURAMENTO_ABRIR_LOTE_SUCCESS = "@faturamento/ABRIR_LOTE_SUCCESS"
export const FATURAMENTO_EXPORTAR_EXCEL_REQUEST = "@faturamento/EXPORTAR_EXCEL_REQUEST"
export const FATURAMENTO_EXPORTAR_EXCEL_SUCCESS = "@faturamento/EXPORTAR_EXCEL_SUCCESS"
export const FATURAMENTO_CONCLUIR_OP_REQUEST = "@faturamento/CONCLUIR_op_REQUEST"
export const FATURAMENTO_CONCLUIR_OP_SUCCESS = "@faturamento/CONCLUIR_op_SUCCESS"
export const FATURAMENTO_ERROR = "@faturamento/ERROR";

// PRODUCAO
export const PRODUCAO_GET_DADOS_INICIAIS_REQUEST = "@producao/GET_DADOS_INICIAIS_REQUEST"
export const PRODUCAO_GET_DADOS_INICIAIS_SUCCESS = "@producao/GET_DADOS_INICIAIS_SUCCESS";
export const PRODUCAO_GERAR_RELATORIO_REQUEST = "@producao/RELATORIO_REQUEST"
export const PRODUCAO_GERAR_RELATORIO_SUCCESS = "@producao/RELATORIO_SUCCESS"
export const PRODUCAO_PESQUISAR_DADOS_REQUEST = "@producao/DADOS_REQUEST"
export const PRODUCAO_PESQUISAR_DADOS_SUCCESS = "@producao/DADOS_SUCCESS"
export const PRODUCAO_ERROR = "@producao/ERROR"

// METAS
export const METAS_LIST_REQUEST = "@metas/LIST_REQUEST";
export const METAS_LIST_SUCCESS = "@metas/LIST_SUCCESS";
export const METAS_PREPARE_NEW_REQUEST = "@metas/PREPARE_NEW_REQUEST";
export const METAS_PREPARE_NEW_SUCCESS = "@metas/PREPARE_NEW_SUCCESS";
export const METAS_PREPARE_EDIT_REQUEST = "@metas/PREPARE_EDIT_REQUEST";
export const METAS_PREPARE_EDIT_SUCCESS = "@metas/PREPARE_EDIT_SUCCESS";
export const METAS_EDIT_REQUEST = "@metas/EDIT_REQUEST";
export const METAS_EDIT_SUCCESS = "@metas/EDIT_SUCCESS";
export const METAS_DELETE_REQUEST = "@metas/DELETE_REQUEST";
export const METAS_DELETE_SUCCESS = "@metas/DELETE_SUCCESS";
export const METAS_NEW_REQUEST = "@metas/NEW_REQUEST";
export const METAS_NEW_SUCCESS = "@metas/NEW_SUCCESS";
export const METAS_ERROR = "@metas/ERROR";

//
export const ALMOXARIFADO_LIST_REQUEST = "@almoxarifado/LIST_RESQUEST"
export const ALMOXARIFADO_LIST_SUCCESS = "@almoxarifado/LIST_SUCCESS"
export const ALMOXARIFADO_SET_OPEN_REQUEST = "@almoxarifado/SET_OPEN_REQUEST"
export const ALMOXARIFADO_SET_OPEN_SUCCESS = "@almoxarifado/SET_OPEN_SUCCESS"
export const ALMOXARIFADO_CHANGE_PAGINATION_REQUEST = "@almoxarifado/CHANGE_PAGINATION_REQUEST"
export const ALMOXARIFADO_CHANGE_PAGINATION_SUCCESS = "@almoxarifado/CHANGE_PAGINATION_SUCCESS"
export const ALMOXARIFADO_LIST_MATERIAIS_REQUEST = "@almoxarifado/LIST_MATERIAIS_REQUEST"
export const ALMOXARIFADO_LIST_MATERIAIS_SUCCESS = "@almoxarifado/LIST_MATERIAIS_SUCCESS"
export const ALMOXARIFADO_ERROR = "@almoxarifado/ERROR";

//DASHBOARD PROGRAMACAO
export const DASH_PROGRAMACAO_LIST_REQUEST = "@programacao/LIST_RESQUEST"
export const DASH_PROGRAMACAO_LIST_SUCCESS = "@programacao/LIST_SUCCESS"
export const DASH_PROGRAMACAO_ERROR = "@programacao/ERROR";

//TELA ROMANEIO
export const ROMANEIO_LIST_REQUEST = "@romaneio/LIST_REQUEST"
export const ROMANEIO_LIST_SUCCESS = "@romaneio/LIST_SUCCESS"
export const ROMANEIO_EXPORTAR_LISTAGEM_REQUEST = "@romaneio/EXPORTAR_LISTAGEM_REQUEST"
export const ROMANEIO_EXPORTAR_LISTAGEM_SUCCESS = "@romaneio/EXPORTAR_LISTAGEM_SUCCESS"
export const ROMANEIO_PREPARE_EDIT_REQUEST = "@romaneio/PREPARE_EDIT_REQUEST"
export const ROMANEIO_PREPARE_EDIT_SUCCESS = "@romaneio/PREPARE_EDIT_SUCCESS"
export const ROMANEIO_ABRIR_STATUS_REQUEST = "@romaneio/PREPARE_ABRIR_STATUS_REQUEST"
export const ROMANEIO_ABRIR_STATUS_SUCCESS = "@romaneio/PREPARE_ABRIR_STATUS_SUCCESS"
export const ROMANEIO_FECHAR_STATUS_REQUEST = "@romaneio/PREPARE_FECHAR_STATUS_REQUEST"
export const ROMANEIO_FECHAR_STATUS_SUCCESS = "@romaneio/PREPARE_FECHAR_STATUS_SUCCESS"
export const ROMANEIO_MUDAR_VOLUME_REQUEST = "@romaneio/MUDAR_VOLUME_REQUEST"
export const ROMANEIO_MUDAR_VOLUME_SUCCESS = "@romaneio/MUDAR_VOLUME_SUCCESS"
export const ROMANEIO_LISTAR_LOTES_REQUEST = "@romaneio/LISTAR_LOTES_REQUEST"
export const ROMANEIO_LISTAR_LOTES_SUCCESS = "@romaneio/LISTAR_LOTES_SUCCESS"
export const ROMANEIO_EDITAR_LOTES_REQUEST = "@romaneio/EDITAR_LOTES_REQUEST"
export const ROMANEIO_EDITAR_LOTES_SUCCESS = "@romaneio/EDITAR_LOTES_SUCCESS"
export const ROMANEIO_HISTORICO_REQUEST = "@romaneio/HISTORICO_REQUEST"
export const ROMANEIO_HISTORICO_SUCCESS = "@romaneio/HISTORICO_SUCCESS"
export const ROMANEIO_EXPORTAR_REQUEST = "@romaneio/EXPORTAR_REQUEST"
export const ROMANEIO_EXPORTAR_SUCCESS = "@romaneio/EXPORTAR_SUCCESS"
export const ROMANEIO_GERAR_NFF_REQUEST = "@romaneio/GERAR_NFF_REQUEST"
export const ROMANEIO_GERAR_NFF_SUCCESS = "@romaneio/GERAR_NFF_SUCCESS"
export const ROMANEIO_CONSULTAR_STATUS_INTEGRACAO_REQUEST = "@romaneio/CONSULTAR_STATUS_INTEGRACAO_REQUEST"
export const ROMANEIO_CONSULTAR_STATUS_INTEGRACAO_SUCCESS = "@romaneio/CONSULTAR_STATUS_INTEGRACAO_SUCCESS"
export const ROMANEIO_EDITAR_NFS_REQUEST = "@romaneio/EDITAR_NF_REQUEST"
export const ROMANEIO_EDITAR_NFS_SUCCESS = "@romaneio/EDITAR_NF_SUCCESS"
export const ROMANEIO_EXPORTAR_XLSX_REQUEST = "@romaneio/EXPORTAR_XLSX_REQUEST"
export const ROMANEIO_EXPORTAR_XLSX_SUCCESS = "@romaneio/EXPORTAR_XLSX_SUCCESS"
export const ROMANEIO_ERROR = "@romaneio/ERROR"

// RELATORIOS
export const RELATORIOS_GET_DADOS_INICIAIS_REQUEST = "@relatorios/GET_DADOS_INICIAIS_REQUEST";
export const RELATORIOS_GET_DADOS_INICIAIS_SUCCESS = "@relatorios/GET_DADOS_INICIAIS_SUCCESS";
export const RELATORIOS_GERAR_SERIAL_REQUEST = "@relatorios/SERIAL_REQUEST"
export const RELATORIOS_GERAR_SERIAL_SUCCESS = "@relatorios/SERIAL_SUCCESS"
export const RELATORIOS_PESQUISAR_DADOS_REQUEST = "@relatorios/DADOS_REQUEST"
export const RELATORIOS_PESQUISAR_DADOS_SUCCESS = "@relatorios/DADOS_SUCCESS"
export const RELATORIOS_ERROR = "@relatorios/ERROR"

// ORDEM DE FABRICAÇÃO
export const ORDEM_FABRICACAO_LIST_REQUEST = "@ordemFabricacao/LIST_REQUEST"
export const ORDEM_FABRICACAO_LIST_SUCCESS = "@ordemFabricacao/LIST_SUCCESS"
export const ORDEM_FABRICACAO_IMPRIMIR_ETIQUETA_REQUEST = "@ordemFabricacao/IMPRIMIR_ETIQUETA_REQUEST"
export const ORDEM_FABRICACAO_IMPRIMIR_ETIQUETA_SUCCESS = "@ordemFabricacao/IMPRIMIR_ETIQUETA_SUCCESS"
export const ORDEM_FABRICACAO_FOLHA_IMPRESSAO_REQUEST = "@ordemFabricacao/FOLHA_IMPRESSAO_REQUEST"
export const ORDEM_FABRICACAO_FOLHA_IMPRESSAO_SUCCESS = "@ordemFabricacao/FOLHA_IMPRESSAO_SUCCESS"
export const ORDEM_FABRICACAO_EXPORTAR_REQUEST = "@ordemFabricacao/EXPORTAR_REQUEST"
export const ORDEM_FABRICACAO_EXPORTAR_SUCCESS = "@ordemFabricacao/EXPORTAR_SUCCESS"
export const ORDEM_FABRICACAO_MATERIAS_PRIMAS_REQUEST = "@ordemFabricacao/MATERIAS_PRIMAS_REQUEST"
export const ORDEM_FABRICACAO_MATERIAS_PRIMAS_SUCCESS = "@ordemFabricacao/MATERIAS_PRIMAS_SUCCESS"
export const ORDEM_FABRICACAO_ENVIAR_SEPARACAO_REQUEST = "@ordemFabricacao/ENVIAR_SEPARACAO_REQUEST"
export const ORDEM_FABRICACAO_ENVIAR_SEPARACAO_SUCCESS = "@ordemFabricacao/ENVIAR_SEPARACAO_SUCCESS"
export const ORDEM_FABRICACAO_HISTORICO_IMPRESSAO_REQUEST = "@ordemFabricacao/HISTORICO_IMPRESSAO_REQUEST"
export const ORDEM_FABRICACAO_HISTORICO_IMPRESSAO_SUCCESS = "@ordemFabricacao/HISTORICO_IMPRESSAO_SUCCESS"
export const ORDEM_FABRICACAO_ALTERAR_QUANTIDADE_REQUEST = "@ordemFabricacao/ALTERAR_QUANTIDADE_REQUEST"
export const ORDEM_FABRICACAO_ALTERAR_QUANTIDADE_SUCCESS = "@ordemFabricacao/ALTERAR_QUANTIDADE_SUCCESS"
export const ORDEM_FABRICACAO_FOLHA_IMPRESSAO_DATA_REQUEST = "@ordemFabricacao/FOLHA_IMPRESSAO_DATA_REQUEST"
export const ORDEM_FABRICACAO_FOLHA_IMPRESSAO_DATA_SUCCESS = "@ordemFabricacao/FOLHA_IMPRESSAO_DATA_SUCCESS"
export const ORDEM_FABRICACAO_CANCELAR_REQUEST = "@ordemFabricacao/CANCELAR_REQUEST"
export const ORDEM_FABRICACAO_CANCELAR_SUCCESS = "@ordemFabricacao/CANCELAR_SUCCESS"
export const ORDEM_FABRICACAO_ERROR = "@ordemFabricacao/ERROR"

// MOTIVOS DE PARADA
export const MOTIVO_DE_PARADA_LIST_REQUEST = "@motivoParada/LIST_REQUEST"
export const MOTIVO_DE_PARADA_LIST_SUCCESS = "@motivoParada/LIST_SUCCESS"
export const MOTIVO_DE_PARADA_DELETE_REQUEST = "@motivoParada/DELETE_REQUEST"
export const MOTIVO_DE_PARADA_DELETE_SUCCESS = "@motivoParada/DELETE_SUCCESS"
export const MOTIVO_DE_PARADA_PREPARE_EDIT_REQUEST = "@motivoParada/PREPARE_EDIT_REQUEST"
export const MOTIVO_DE_PARADA_PREPARE_EDIT_SUCCESS = "@motivoParada/PREPARE_EDIT_SUCCESS"
export const MOTIVO_DE_PARADA_PREPARE_NEW_REQUEST = "@motivoParada/PREPARE_NEW_REQUEST"
export const MOTIVO_DE_PARADA_PREPARE_NEW_SUCCESS = "@motivoParada/PREPARE_NEW_SUCCESS"
export const MOTIVO_DE_PARADA_EDIT_REQUEST = "@motivoParada/EDIT_REQUEST"
export const MOTIVO_DE_PARADA_EDIT_SUCCESS = "@motivoParada/EDIT_SUCCESS"
export const MOTIVO_DE_PARADA_NEW_REQUEST = "@motivoParada/NEW_REQUEST"
export const MOTIVO_DE_PARADA_NEW_SUCCESS = "@motivoParada/NEW_SUCCESS"
export const MOTIVO_DE_PARADA_ATIVAR_OU_DESATIVAR_REQUEST = "@motivoParada/ATIVAR_DESATIVAR_REQUEST";
export const MOTIVO_DE_PARADA_ERROR = "@motivoParada/ERROR"

// TEMPO APONTAMENTO
export const TEMPO_APONTAMENTO_LIST_REQUEST = "@tempoApontamento/LIST_REQUEST"
export const TEMPO_APONTAMENTO_LIST_SUCCESS = "@tempoApontamento/LIST_SUCCESS"
export const TEMPO_APONTAMENTO_EDIT_REQUEST = "@tempoApontamento/EDIT_REQUEST"
export const TEMPO_APONTAMENTO_EDIT_SUCCESS = "@tempoApontamento/EDIT_SUCCESS"
export const TEMPO_APONTAMENTO_ERROR = "@tempoApontamento/ERROR"

// REIMPRESSAO DE ETIQUETAS
export const REIMPRESSAO_ETIQUETAS_GET_IMPRESSORAS_REQUEST = "@reimpressaoEtiquetas/GET_IMPRESSORAS_REQUEST"
export const REIMPRESSAO_ETIQUETAS_GET_IMPRESSORAS_SUCCESS = "@reimpressaoEtiquetas/GET_IMPRESSORAS_SUCCESS"
export const REIMPRESSAO_ETIQUETAS_REIMPRIMIR_REQUEST = "@reimpressaoEtiquetas/REIMPRIMIR_REQUEST"
export const REIMPRESSAO_ETIQUETAS_REIMPRIMIR_SUCCESS = "@reimpressaoEtiquetas/REIMPRIMIR_SUCCESS"
export const REIMPRESSAO_ETIQUETAS_PESQUISAR_DADOS_REQUEST = "@reimpressaoEtiquetas/PESQUISAR_DADOS_REQUEST"
export const REIMPRESSAO_ETIQUETAS_PESQUISAR_DADOS_SUCCESS = "@reimpressaoEtiquetas/PESQUISAR_DADOS_SUCCESS"
export const REIMPRESSAO_ETIQUETAS_ERROR = "@reimpressaoEtiquetas/ERROR"

// TURNOS
export const TURNOS_LISTAR_REQUEST = "@turnos/LISTAR_REQUEST"
export const TURNOS_LISTAR_SUCCESS = "@turnos/LISTAR_SUCCESS"
export const TURNOS_PREPARE_EDIT_REQUEST = "@turnos/PREPARE_EDIT_REQUEST"
export const TURNOS_PREPARE_EDIT_SUCCESS = "@turnos/PREPARE_EDIT_SUCCESS"
export const TURNOS_PREPARE_NEW_REQUEST = "@turnos/PREPARE_NEW_REQUEST"
export const TURNOS_PREPARE_NEW_SUCCESS = "@turnos/PREPARE_NEW_SUCCESS"
export const TURNOS_EDIT_REQUEST = "@turnos/EDIT_REQUEST"
export const TURNOS_EDIT_SUCCESS = "@turnos/EDIT_SUCCESS"
export const TURNOS_NOVO_REQUEST = "@turnos/NOVO_REQUEST"
export const TURNOS_NOVO_SUCCESS = "@turnos/NOVO_SUCCESS"
export const TURNOS_DELETAR_REQUEST = "@turnos/DELETAR_REQUEST"
export const TURNOS_DELETAR_SUCCESS = "@turnos/DELETAR_SUCCESS"
export const TURNOS_ERROR = "@turnos/ERROR"


// RECEBIMENTO
export const RECEBIMENTO_LIST_REQUEST = "@recebimento/LIST_REQUEST"
export const RECEBIMENTO_LIST_SUCCESS = "@recebimento/LIST_SUCCESS"
export const RECEBIMENTO_CONCLUIR_MANUALMENTE_REQUEST = "@recebimento/CONCLUIR_MANUALMENTE_REQUEST"
export const RECEBIMENTO_CONCLUIR_MANUALMENTE_SUCCESS = "@recebimento/CONCLUIR_MANUALMENTE_SUCCESS"
export const RECEBIMENTO_ERROR = "@recebimento/ERROR"
// PLANEJAMENTO DIARIO
export const PLANEJAMENTO_DIARIO_LISTAR_REQUEST = "@planejamento_diario/LISTAR_REQUEST"
export const PLANEJAMENTO_DIARIO_LISTAR_SUCCESS = "@planejamento_diario/LISTAR_SUCCESS"
export const PLANEJAMENTO_DIARIO_PREPARE_EDIT_REQUEST = "@planejamento_diario/PREPARE_EDIT_REQUEST"
export const PLANEJAMENTO_DIARIO_PREPARE_EDIT_SUCCESS = "@planejamento_diario/PREPARE_EDIT_SUCCESS"
export const PLANEJAMENTO_DIARIO_PREPARE_NEW_REQUEST = "@planejamento_diario/PREPARE_NEW_REQUEST"
export const PLANEJAMENTO_DIARIO_PREPARE_NEW_SUCCESS = "@planejamento_diario/PREPARE_NEW_SUCCESS"
export const PLANEJAMENTO_DIARIO_EDIT_REQUEST = "@planejamento_diario/EDIT_REQUEST"
export const PLANEJAMENTO_DIARIO_EDIT_SUCCESS = "@planejamento_diario/EDIT_SUCCESS"
export const PLANEJAMENTO_DIARIO_NOVO_REQUEST = "@planejamento_diario/NOVO_REQUEST"
export const PLANEJAMENTO_DIARIO_NOVO_SUCCESS = "@planejamento_diario/NOVO_SUCCESS"
export const PLANEJAMENTO_DIARIO_DELETAR_REQUEST = "@planejamento_diario/DELETAR_REQUEST"
export const PLANEJAMENTO_DIARIO_DELETAR_SUCCESS = "@planejamento_diario/DELETAR_SUCCESS"
export const PLANEJAMENTO_DIARIO_EXPORTAR_REQUEST = "@planejamento_diario/EXPORTAR_REQUEST"
export const PLANEJAMENTO_DIARIO_EXPORTAR_SUCCESS = "@planejamento_diario/EXPORTAR_SUCCESS"
export const PLANEJAMENTO_DIARIO_ERROR = "@planejamento_diario/ERROR"

// MOTIVOS DE PARADA
export const PARADA_LIST_REQUEST = "@parada/LIST_REQUEST";
export const PARADA_LIST_SUCCESS = "@parada/LIST_SUCCESS";
export const PARADA_LIST_MOTIVO_PARADA_REQUEST = "@parada/LIST_MOTIVO_PARADA_REQUEST";
export const PARADA_LIST_MOTIVO_PARADA_SUCCESS = "@parada/LIST_MOTIVO_PARADA_SUCCESS";
export const PARADA_LIST_UPDATE_MOTIVO_REQUEST = "@parada/LIST_UPDATE_MOTIVO_REQUEST";
export const PARADA_LIST_UPDATE_MOTIVO_SUCCESS = "@parada/LIST_UPDATE_MOTIVO_SUCCESS";
export const PARADA_DIVIDIR_REQUEST = "@parada/DIVIDIR_REQUEST";
export const PARADA_DIVIDIR_SUCCESS = "@parada/DIVIDIR_SUCCESS";
export const PARADA_ERROR = "@parada/ERROR";

// APONTAMENTOS PENDENTES
export const APONTAMENTOS_PENDENTES_LIST_REQUEST = "@apontamentosPendentes/LIST_REQUEST"
export const APONTAMENTOS_PENDENTES_LIST_SUCCESS = "@apontamentosPendentes/LIST_SUCCESS"
export const APONTAMENTOS_PENDENTES_EXPORTAR_REQUEST = "@apontamentosPendentes/EXPORTAR_REQUEST"
export const APONTAMENTOS_PENDENTES_EXPORTAR_SUCCESS = "@apontamentosPendentes/EXPORTAR_SUCCESS"
export const APONTAMENTOS_PENDENTES_ERROR = "@apontamentosPendentes/ERROR"

// ASAICHI
export const ASAICHI_LIST_REQUEST = "@asaichi/LIST_REQUEST";
export const ASAICHI_LIST_SUCCESS = "@asaichi/LIST_SUCCESS";
export const ASAICHI_TABELA_PRODUCAO_REQUEST = "@asaichi/TABELA_PRODUCAO_REQUEST";
export const ASAICHI_TABELA_PRODUCAO_SUCCESS = "@asaichi/TABELA_PRODUCAO_SUCCESS";
export const ASAICHI_TABELA_DEFEITOS_REQUEST = "@asaichi/TABELA_DEFEITOS_REQUEST";
export const ASAICHI_TABELA_DEFEITOS_SUCCESS = "@asaichi/TABELA_DEFEITOS_SUCCESS";
export const ASAICHI_TABELA_PRODUTIVIDADE_REQUEST = "@asaichi/TABELA_PRODUTIVIDADE_REQUEST";
export const ASAICHI_TABELA_PRODUTIVIDADE_SUCCESS = "@asaichi/TABELA_PRODUTIVIDADE_SUCCESS";
export const ASAICHI_PRODUCAO_DIARIA_REQUEST = "@asaichi/PRODUCAO_DIARIA_REQUEST";
export const ASAICHI_PRODUCAO_DIARIA_SUCCESS = "@asaichi/PRODUCAO_DIARIA_SUCCESS";
export const ASAICHI_PRODUCAO_SEMANAL_REQUEST = "@asaichi/PRODUCAO_SEMANAL_REQUEST";
export const ASAICHI_PRODUCAO_SEMANAL_SUCCESS = "@asaichi/PRODUCAO_SEMANAL_SUCCESS";
export const ASAICHI_PRODUCAO_MENSAL_REQUEST = "@asaichi/PRODUCAO_MENSAL_REQUEST";
export const ASAICHI_PRODUCAO_MENSAL_SUCCESS = "@asaichi/PRODUCAO_MENSAL_SUCCESS";
export const ASAICHI_GRAFICO_DEFEITOS_REQUEST = "@asaichi/GRAFICO_DEFEITOS_REQUEST";
export const ASAICHI_GRAFICO_DEFEITOS_SUCCESS = "@asaichi/GRAFICO_DEFEITOS_SUCCESS";
export const ASAICHI_ERROR = "@asaichi/ERROR";

// TRANSFORMACAO LOTES
export const TRANSFORMACAO_LOTE_BUSCAR_CAIXAS_REQUEST = "@transformacaoLote/BUSCAR_CAIXAS_REQUEST"
export const TRANSFORMACAO_LOTE_BUSCAR_CAIXAS_SUCCESS = "@transformacaoLote/BUSCAR_CAIXAS_SUCCESS"
export const TRANSFORMACAO_LOTE_DIVIDIR_REQUEST = "@transformacaoLote/DIVIDIR_REQUEST"
export const TRANSFORMACAO_LOTE_DIVIDIR_SUCCESS = "@transformacaoLote/DIVIDIR_SUCCESS"
export const TRANSFORMACAO_LOTE_AGRUPAR_REQUEST = "@transformacaoLote/AGRUPAR_REQUEST"
export const TRANSFORMACAO_LOTE_AGRUPAR_SUCCESS = "@transformacaoLote/AGRUPAR_SUCCESS"
export const TRANSFORMACAO_LOTE_PESQUISAR_LOTES_REQUEST = "@transformacaoLote/PESQUISAR_LOTES_REQUEST"
export const TRANSFORMACAO_LOTE_PESQUISAR_LOTES_SUCCESS = "@transformacaoLote/PESQUISAR_LOTES_SUCCESS"
export const TRANSFORMACAO_LOTE_RESETAR = "@transformacaoLote/RESETAR"
export const TRANSFORMACAO_LOTE_ERROR = "@transformacaoLote/ERROR"

// APONTAMENTO DE MATERIAL
export const APONTAMENTO_DE_MATERIAL_LIST_REQUEST = "@apontamentoDeMaterial/LIST_REQUEST"
export const APONTAMENTO_DE_MATERIAL_LIST_SUCCESS = "@apontamentoDeMaterial/LIST_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_BUSCA_ORDENS_DE_PRODUCAO_REQUEST = "@apontamentoDeMaterial/BUSCA_ORDENS_DE_PRODUCAO_REQUEST"
export const APONTAMENTO_DE_MATERIAL_BUSCA_ORDENS_DE_PRODUCAO_SUCCESS = "@apontamentoDeMaterial/BUSCA_ORDENS_DE_PRODUCAO_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_BUSCA_MATERIAIS_REQUEST = "@apontamentoDeMaterial/BUSCA_MATERIAIS_REQUEST"
export const APONTAMENTO_DE_MATERIAL_BUSCA_MATERIAIS_SUCCESS = "@apontamentoDeMaterial/BUSCA_MATERIAIS_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_BUSCA_LOTES_DISPONIVEIS_REQUEST = "@apontamentoDeMaterial/BUSCA_LOTES_DISPONIVEIS_REQUEST"
export const APONTAMENTO_DE_MATERIAL_BUSCA_LOTES_DISPONIVEIS_SUCCESS = "@apontamentoDeMaterial/BUSCA_LOTES_DISPONIVEIS_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_APONTAR_REQUEST = "@apontamentoDeMaterial/APONTAR_REQUEST"
export const APONTAMENTO_DE_MATERIAL_APONTAR_SUCCESS = "@apontamentoDeMaterial/APONTAR_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_IMPORTAR_ARQUIVO_REQUEST = "@apontamentoDeMaterial/IMPORTAR_ARQUIVO_REQUEST"
export const APONTAMENTO_DE_MATERIAL_IMPORTAR_ARQUIVO_SUCCESS = "@apontamentoDeMaterial/IMPORTAR_ARQUIVO_SUCCESS"
export const APONTAMENTO_DE_MATERIAL_ERROR = "@apontamentoDeMaterial/ERROR"
